// <auto-generated />
using System;
using DistroTimer.Shared.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistroTimer.Shared.Migrations
{
    [DbContext(typeof(DistroContext))]
    partial class DistroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("DistroTimer.Shared.Models.DistroData", b =>
                {
                    b.Property<int>("DistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DistroName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DistroId");

                    b.HasIndex("UserId");

                    b.ToTable("Distros");
                });

            modelBuilder.Entity("DistroTimer.Shared.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DistroTimer.Shared.Models.DistroData", b =>
                {
                    b.HasOne("DistroTimer.Shared.Models.User", null)
                        .WithMany("Distros")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DistroTimer.Shared.Models.User", b =>
                {
                    b.Navigation("Distros");
                });
#pragma warning restore 612, 618
        }
    }
}
